final List chat = [
  {
    'nom': "Merveille",
    "prenom": "Merveille",
    "message": "Coucou",
    "appel": "Entrant",
    "date": "25 Mar.",
    "profil": "images/profils/img1.jpg",
    "storie": "images/stories/img1.jpg",
  },
  {
    "nom": "Aline",
    "prenom": "Ola",
    "message": "Je viens déja",
    "appel": "Entrant",
    "date": "20 Mar.",
    "profil": "images/profils/img2.jpg",
    "storie": "images/stories/img2.jpg",
  },
  {
    "nom": "Oussou",
    "prenom": "Godwill",
    "message": "BCMF va nous tuer",
    "appel": "Sortant",
    "date": "Aujourd'hui",
    "profil": "images/profils/img3.jpg",
    "storie": "images/stories/img3.jpg",
  },
  {
    "nom": "Tossavi",
    "prenom": "Emery",
    "message": "ok",
    "appel": "Manqué",
    "date": "Aujourd'hui",
    "profil": "images/profils/img4.jpg",
    "storie": "images/stories/img4.jpg",
  },
  {
    "nom": "Ta",
    "prenom": "Daronne",
    "message": "Tu reviens quand?",
    "appel": "Sortant",
    "date": "25 oct",
    "profil": "images/profils/img5.jpg",
    "storie": "images/stories/img5.jpg",
  },
  {
    "nom": "Ma",
    "prenom": "Choupinette",
    "message": "Je t'aime chéri",
    "appel": "Entrant",
    "date": "Hier",
    "profil": "images/profils/img6.jpg",
    "storie": "images/stories/img6.jpg",
  },
  {
    "nom": "Richard",
    "prenom": "Zed",
    "message": "ok bro",
    "appel": "Sortant",
    "date": "25 nov",
    "profil": "images/profils/img7.jpg",
    "storie": "images/stories/img7.jpg",
  },
  {
    "nom": "Tobi",
    "prenom": "La Rose",
    "message": "????",
    "appel": "Sortant",
    "date": "05 oct",
    "profil": "images/profils/img8.jpg",
    "storie": "images/stories/img8.jpg",
  },
  {
    "nom": "Noble",
    "prenom": "Mandela",
    "message": "J'ai confiance en toi",
    "appel": "Sortant",
    "date": "05 jan",
    "profil": "images/profils/img9.jpg",
    "storie": "images/stories/img9.jpg",
  },
  {
    "nom": "Laud",
    "prenom": "Roch",
    "message": "Prête moi ton compte binance stp",
    "appel": "Entrant",
    "date": "25 oct",
    "profil": "images/profils/img10.jpg",
    "storie": "images/stories/img10.jpg",
  },
];